PINECONE_API_KEY: 8936e782-c356-499c-8351-9225216e450f
PINECONE_ENVIRONMENT: us-west4-gcp-free


OPENAI_API_KEY: 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

#####################------------------TOOLS KEY-------------------------########################
#If you have google api key and CSE key, use this
GOOGLE_API_KEY: AIzaSyBsk9GR6KbXUBI1oJzfxPHuLuubrQ6krcs
SEARCH_ENGINE_ID: 411d4e825e3f44a7b

# IF YOU DONT HAVE GOOGLE SERACH KEY, USE THIS
SERP_API_KEY: YOUR_SERP_API_KEY

#ENTER YOUR EMAIL CREDENTIALS TO ACCESS EMAIL TOOL
EMAIL_ADDRESS: YOUR_EMAIL_ADDRESS
EMAIL_PASSWORD: YOUR_EMAIL_APP_PASSWORD #get the app password from (https://myaccount.google.com/apppasswords)
EMAIL_SMTP_HOST: smtp.gmail.com #Change the SMTP host if not using Gmail
EMAIL_SMTP_PORT: 587 #Change the SMTP port if not using Gmail
EMAIL_IMAP_SERVER: imap.gmail.com #Change the IMAP Host if not using Gmail
EMAIL_SIGNATURE: Email sent by SuperAGI
EMAIL_DRAFT_MODE_WITH_FOLDER: YOUR_DRAFTS_FOLDER
EMAIL_ATTACHMENT_BASE_PATH: YOUR_DIRECTORY_FOR_EMAIL_ATTACHMENTS

#DATABASE INFO
MAX_TOOL_TOKEN_LIMIT: 800

# redis details
DB_NAME: super_agi_main
POSTGRES_URL: super__postgres
DB_USERNAME: superagi
DB_PASSWORD: password
REDIS_URL: "super__redis:6379"

#STORAGE TYPE ("FILE" or "S3")
STORAGE_TYPE: "FILE"

#STORAGE INFO FOR FILES
RESOURCES_INPUT_ROOT_DIR: workspace/input
RESOURCES_OUTPUT_ROOT_DIR: workspace/output

#S3 RELATED DETAILS ONLY WHEN STORAGE_TYPE IS "S3"
BUCKET_NAME:
S3_KEY:
